/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra17_2014_pnrs1_rtrk_taskmanager_taskmanager_StatisticsNative */

#ifndef _Included_ra17_2014_pnrs1_rtrk_taskmanager_taskmanager_StatisticsNative
#define _Included_ra17_2014_pnrs1_rtrk_taskmanager_taskmanager_StatisticsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra17_2014_pnrs1_rtrk_taskmanager_taskmanager_StatisticsNative
 * Method:    getStatistics
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_ra17_12014_pnrs1_rtrk_taskmanager_taskmanager_StatisticsNative_getStatistics
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
